M48
; DRILL file {KiCad 9.0.3+dfsg-1} date 2026-02-21T17:58:44+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-21T17:58:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
%
G90
G05
T1
X35.56Y-22.86
X43.18Y-20.32
X48.26Y-20.32
X55.88Y-17.78
M30
